settings:
  legacy:
    force: false
    interval: 0s
schema:
- name: gae-go-grpc
  path: ./app/api
  commands:
    run:
      status: true
  watcher:
    extensions:
      - go
    paths:
      - .
      - ../../internal
