version: '3.7'

services:
  api:
    build:
      context: ./containers/api
    working_dir: /go/src/github.com/110y/gae-go-grpc
    tty: true
    stdin_open: true
    privileged: true
    ports:
      - ${GRPC_PORT}:5000
      - ${HTTP_PORT}:8080
    environment:
      - GO111MODULE=on
      - HISTFILE=/go/src/github.com/110y/gae-go-grpc/tmp/.sh_history_api
      - DATASTORE_EMULATOR_HOST=db:3000
      - GCP_PROJECT_ID=${GCP_PROJECT_ID}
      - ENABLE_STACKDRIVER_TRACE=${ENABLE_STACKDRIVER_TRACE}
      - APP_ENGINE_NAMESPACE=${APP_ENGINE_NAMESPACE}
    volumes:
      - ${GOPATH}/src/github.com/110y/gae-go-grpc:/go/src/github.com/110y/gae-go-grpc:cached
      - ${GOPATH}/pkg/mod:/go/pkg/mod:cached
    command: realize start

  db:
    build:
      context: ./containers/db
    ports:
      - ${DB_PORT}:3000
    environment:
      - CLOUDSDK_CORE_PROJECT=${GCP_PROJECT_ID}
    command: gcloud beta emulators datastore start --host-port 0.0.0.0:3000 --store-on-disk --data-dir /datastore --consistency 0.8
    volumes:
      - datastore:/datastore

  protoc:
    build:
      context: ./containers/protoc
    working_dir: /go/src/github.com/110y/gae-go-grpc
    volumes:
      - ${GOPATH}/src/github.com/110y/gae-go-grpc:/go/src/github.com/110y/gae-go-grpc:cached

volumes:
  datastore: {}
